# SPDX-FileCopyrightText: 2013 The glucometerutils Authors
#
# SPDX-License-Identifier: MIT

dist: xenial

language: python

matrix:
  include:
    - python: 3.7
    - python: 3.8
    - python: 3.9
      env: PYTEST_OPTIONS="--mypy"
    - python: 3.10-dev

install:
  - pip install .[all]

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - libudev-dev

script:
  - pytest $PYTEST_OPTIONS glucometerutils
